### ISSUE TITLE
app crash when resize window

### ISSUE THREAD

**Issue by mosayed01** [TheChance101/AAY-chart#17]
## Exception
![image](https://github.com/TheChance101/AAY-chart/assets/83292287/b59c8cc7-ea42-4d1a-afca-17cae5674836)

## Cause
using this function throw this exception.
![image](https://github.com/TheChance101/AAY-chart/assets/83292287/aadcee39-0538-4385-9ed7-fa978237f731)
```
public fun Float.coerceIn(minimumValue: Float, maximumValue: Float): Float {
    if (minimumValue > maximumValue) throw IllegalArgumentException("Cannot coerce value to an empty range: maximum $maximumValue is less than minimum $minimumValue.")
    if (this < minimumValue) return minimumValue
    if (this > maximumValue) return maximumValue
    return this
}
```

Please think in another way to handle it.
**I suggest always with canvas use ratio.**

**Comment by AndrewAboalhana** [comment]
now i tried to use coerceAtMax and AtLeast and it's working well
