### ISSUE TITLE
[Desktop] Unable to display the chart inside the LazyColumn

### ISSUE THREAD

**Issue by jeffreyrajanofficial** [TheChance101/AAY-chart#86]
Hi, I am not able to render any of the charts in the LazyColumn. Do you have any solution for this?

**Comment by AndrewAboalhana** [comment]
Can you explain the problem you are facing more? and what version of the library that you use

**Comment by AndrewAboalhana** [comment]
here in the lazy column, you need to give it a particular size not fill max size

**Comment by jeffreyrajanofficial** [comment]
My bad, Thanks for pointing it out.
